#!/bin/bash

#######################################################################################################
##SET UP OPTIONS FOR INPUT GAF FILES

while getopts g:i:o: option
do
        case "${option}"
        in

                g) goanna_gaf=${OPTARG};;
                i) ips_gaf=${OPTARG};;
		o) out=${OPTARG};;
        esac
done


sed '1d' $ips_gaf > tmp.gaf
cat  $goanna_gaf tmp.gaf > $out.tsv
rm tmp.gaf
